dbt_amazon:
  outputs:
    dev:
      dataset: DEV
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/dbt_amazon/gcp/amazon_service_account.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: your_project
      threads: 1
      type: bigquery
  target: dev
